deployment:
  tasks:
    - export DEPLOYPATH=/home2/reshaminfo/qr-code/
    - mkdir -p /home2/reshaminfo/qr-code/
    - /bin/cp -R * $DEPLOYPATH
    - cd /home2/reshaminfo/qr-code/
    - export DEPLOYPATH=/home2/reshaminfo/qr.resham.info.np/
    - rm -rf $DEPLOYPATH/js && rm -rf $DEPLOYPATH/css
    - rm -rf $DEPLOYPATH/assets && rm -rf $DEPLOYPATH/assets
    - mkdir $DEPLOYPATH/js && mkdir $DEPLOYPATH/css
    - /bin/cp ./public/js/*.js $DEPLOYPATH/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/css
    - /bin/cp ./public/assets/* $DEPLOYPATH/assets